export const fontStyles = {
  MuseoSans300: 'MuseoSans300',
  MuseoSans500: 'MuseoSans500',
  MuseoSans700: 'MuseoSans700',
  robotoBlack: 'Roboto-Black',
  robotoBlackItalic: 'Roboto-BlackItalic',
  robotoBold: 'Roboto-Bold',
  robotoBoldItalic: 'Roboto-BoldItalic',
  robotoItalic: 'Roboto-Italic',
  robotoLight: 'Roboto-Light',
  robotoLightItalic: 'Roboto-LightItalic',
  robotoMedium: 'Roboto-Medium',
  robotoMediumItalic: 'Roboto-MediumItalic',
  robotoRegular: 'Roboto-Regular',
  robotoThin: 'Roboto-Thin',
  robotoThinItalic: 'Roboto-ThinItalic',
}
